### ISSUE TITLE
Select all/select region?

### ISSUE THREAD

**Issue by carlesso** [mwh/dragon#1]
Hi @mwh, first of all THANK YOU! I was lookgin for something like dragon for a long time... really really thanks.

Do you think it will be possilbe to have dragon support a select all or select region for files in window? I found most of the times I just need to attach 4/5 files to an email, for example, and I'd like to be able to select all from dragon window and drag them into the browser.

**Comment by mwh** [comment]
I don't see any reason that it couldn't – the protocol supports it straightforwardly – although the UI would become more complicated. If you want to work on a patch, go ahead.

**Comment by protist** [comment]
@eigengrau @mwh I'm not sure if I misunderstand this issue. I thought it was to run dragon on a whole bunch of files, select a subset of those files, and drag them all collectively. i.e.

1. `$ dragon foo bar baz`
2. Select `bar` and `baz`
3. Drag both to the target in one motion

Has this been fixed by the patch? I'm not sure what is different.

**Comment by eigengrau** [comment]
@protist Oh, I’m sorry, this was my bad. There was a typo in the commit message merged in #7. It should have said `fixes #2, #3`, not `#1, #2`. Perphaps @mwh can reopen this one.

**Comment by mwh** [comment]
This actually should have been closed almost a year ago with 24242e7, which added the `--all`/`-a` option for dragging out all the files at once.

**Comment by protist** [comment]
@mwh Ah okay. I was thinking more something provided by the GUI to also allow partial selections. Thinking about again it, the `--all` flag probably suffices, and I can pare on the command line instead. Cheers.
