### ISSUE TITLE
Wayland?

### ISSUE THREAD

**Issue by PopeRigby** [mwh/dragon#22]
Will this program support Wayland in the future, or is there a Wayland alternative?

**Comment by niyumard** [comment]
> Will this program support Wayland in the future, or is there a Wayland alternative?

What's your problem with this program? I'm currently using it with Sway under Wayland and since dragon is written in GTK3 it's got support for it.

**Comment by PopeRigby** [comment]
Oh, my bad. It's says in the description that it's for X, so I just assumed it wouldn't work natively through Wayland.

**Comment by niyumard** [comment]
> Oh, my bad. It's says in the description that it's for X, so I just assumed it wouldn't work natively through Wayland.

@mwh Can we have Wayland in description as well?

**Comment by mwh** [comment]
I have not tested it with Wayland, but I suppose as long as GTK+ is doing all the hard parts it will just work. I hadn't really considered it, but plausibly it works anywhere GTK does. If everything does behave properly I can add "or Wayland" to the readme.

**Comment by niyumard** [comment]
> suppose as long as GTK+ is doing all the hard parts it will just work. I hadn't really considered it, but plausibly it

Well most things work perfectly but not everything. In Wayland I can drop multiple files to Telegram app and it works; at the same time I can't drop multiple files to any site on Firefox, it just drops the first file selected.
I've tried using Firefox and dragon under X, This problem doesn't exist there.
Dropping multiple files to Telegram under Wayland works successfully, and I've had no luck dropping files from Thunar to Firefox either (again only one file is dropped), so I think the problem caused by Firefox rather than dragon or Thunar.
