### ISSUE TITLE
Possibility for thumbnails?

### ISSUE THREAD

**Issue by 3291823** [mwh/dragon#25]
Would implementing thumbnails into this program be possible?
TIA.

**Comment by mwh** [comment]
To the extent that GTK+ supports generic thumbnailing for some file types, this could be achievable. Generating thumbnails otherwise is probably out of scope.

Another approach would be that when listing files on the command line each could be accompanied by a path to a thumbnail image (something like `dragon file.pdf --thumb /tmp/file_pdf.png`); that would let thumbnails be generated externally.

Both of these changes would be fairly substantial.

**Comment by mwh** [comment]
This has been resolved in #33 and images (only) will be thumbnailed by GTK+.
