### ISSUE TITLE
always prepends current working directory

### ISSUE THREAD

**Issue by Arifd** [mwh/dragon#29]
I'm trying to use dragon with a file selector dialog such as yad or zenity.

Both give me the same error:
`dragon -x "'$(yad 2>/dev/null --file)'"`
`dragon -x "'$(zenity --file-selection)'"`
> The file `/home/arif/'/home/arif/Downloads/remove-red.png'' does not exist.

(Using the funny quoting in an attempt not be disturbed by paths with spaces)

**Comment by FichteFoll** [comment]
The "funny quoting" is exactly what's causing this. Your shell expands that to `"'/home/arif/Downloads/remove-red.png'"`, which is then interpreted as the literal argument `'/home/arif/Downloads/remove-red.png'`. Since it starts with a non-slash character, it is interpreted as a relative path by dragon (or gtk, rather).

If you expect just a single result from these commands, simply remove the `'`. If you expect multiple, use `xargs`.

**Comment by Arifd** [comment]
Argh! I was so close! Thank you for your help!!
