### ISSUE TITLE
is_uri is too lax, e.g. timestamps are false positives

### ISSUE THREAD

**Issue by kurinoku** [mwh/dragon#44]
I understand why is it coded like that, it's very effective, but, when it comes to some naming conventions like timestamps, for example `some-series-i-was-watching.mkv_[00:19:35.257].png` gets interpreted as a uri

**Comment by mwh** [comment]
This fix will resolve your exact case, but without the _ and [] it would still be a plausible URI and create a URI button. When that happens, `./some-file-10:30` will unambiguously be treated as a local file (because the `/` precedes the `:`) and create a file button.

It's possible the default should have been the other way around when a file with the given name is found in the current directory, regardless of how it looks. That would technically be a breaking change, though unlikely to cause any problem in practice. A drawback would be that there is no workaround to force URL treatment in the way that there is one to force file treatment. For the moment, `./xy:z` will always avoid the issue.
